dnl -*- autoconf -*-

AC_DEFUN([AM_INIT_AUTOMAKE], [
    AUTOMAKE_OPTIONS_ADD="$1"
    : ${PREFIX:=/usr/local}
    AC_SUBST([AUTOMAKE_OPTIONS_ADD])
    AC_SUBST([PREFIX])
    AC_REQUIRE([AC_PROG_INSTALL])
    AC_REQUIRE([AC_PROG_MAKE])
    AC_REQUIRE([AC_PROG_MAKE_SET])
])

AC_DEFUN([AM_SILENT_RULES], [
    AM_CONDITIONAL([_AM_SILENT_RULES], [test "$1" = "yes" || test "$1" = 1])
])
